#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY operations
#

def solve(n, operations):


    total_candies = 0

    for operation in operations:

        a, b, k = operation  # Unpack operation values

        jars_affected = b - a + 1  # Calculate the number of jars involved

        candies_added = k * jars_affected  # Calculate the total candies added

        total_candies += candies_added  # Add to the overall total

    average = total_candies // n  # Calculate the floor of the average

    return average  # Return the integer result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    operations = []

    for _ in range(m):
        operations.append(list(map(int, input().rstrip().split())))

    result = solve(n, operations)

    fptr.write(str(result) + '\n')

    fptr.close()
